version: "3.4"

name: ${PROJECT_NAME}

services:
  caddy:
    image: ${PROJECT_NAME}_caddy
    container_name: ${PROJECT_NAME}_caddy
    build:
      context: ../
      dockerfile: docker/Dockerfile
      target: caddy
    depends_on:
      - php
    ports:
      - ${SERVER_PORT}:80
    volumes:
      - ../:/var/www/app

  mysql:
    image: mysql:8.1
    container_name: ${PROJECT_NAME}_mysql
    build:
      context: ../
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./mysql_volume/:/var/lib/mysql

  php:
    image: ${PROJECT_NAME}_php
    container_name: ${PROJECT_NAME}_php
    build:
      context: ../
      dockerfile: docker/Dockerfile
      target: php_dev
    depends_on:
      - mysql
    volumes:
      - ../:/var/www/app
